packages:
  - 'packages/sanity-config'
  # Keep other packages (for example packages/hydrogen-sanity) outside of the
  # workspace so tooling like `netlify dev` sees a single project.
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - canvas
  - core-js
  - cpu-features
  - esbuild
  - netlify-cli
  - sharp
  - ssh2
  - unix-dgram

patchedDependencies:
  react-refractor@4.0.0: patches/react-refractor@4.0.0.patch
