packages:
  - packages/**

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - canvas
  - core-js
  - cpu-features
  - esbuild
  - netlify-cli
  - sharp
  - ssh2
  - unix-dgram

patchedDependencies:
  '@sanity/presentation': patches/@sanity__presentation.patch
  react-refractor@4.0.0: patches/react-refractor@4.0.0.patch
