export const googleProductCategories = [
  'Animals & Pet Supplies > Pet Supplies',
  'Apparel & Accessories > Clothing',
  'Apparel & Accessories > Shoes',
  'Apparel & Accessories > Jewelry',
  'Arts & Entertainment > Hobbies & Creative Arts',
  'Baby & Toddler > Nursery Furniture',
  'Business & Industrial',
  'Cameras & Optics',
  'Electronics',
  'Food, Beverages & Tobacco',
  'Furniture',
  'Hardware',
  'Health & Beauty',
  'Home & Garden',
  'Luggage & Bags',
  'Mature',
  'Media > Books',
  'Media > Music',
  'Media > Videos',
  'Office Supplies',
  'Religious & Ceremonial',
  'Software',
  'Sporting Goods',
  'Toys & Games',
  'Vehicles & Parts > Vehicle Parts & Accessories > Motor Vehicle Parts',
]
