import {defineField, defineType} from 'sanity'
import ReferenceCodeInput from '../../components/inputs/ReferenceCodeInput'
import {generateReferenceCode} from '../../../../../shared/referenceCodes'

const API_VERSION = '2024-10-01'

export default defineType({
  name: 'vendor',
  title: 'Vendor',
  type: 'document',
  groups: [
    {name: 'profile', title: 'Profile', default: true},
    {name: 'contacts', title: 'Contacts'},
    {name: 'addresses', title: 'Addresses'},
    {name: 'pricing', title: 'Pricing & Terms'},
    {name: 'tax', title: 'Tax'},
    {name: 'orderSettings', title: 'Order Settings'},
    {name: 'portal', title: 'Portal Access'},
    {name: 'tracking', title: 'Internal Tracking'},
  ],
  fields: [
    defineField({
      name: 'vendorNumber',
      title: 'Vendor Number',
      type: 'string',
      readOnly: true,
      group: 'profile',
      components: {input: ReferenceCodeInput},
      description: 'Auto-generated reference (VEN-XXXXXX).',
      initialValue: async ({getClient}) => {
        const client = getClient?.({apiVersion: API_VERSION})
        return generateReferenceCode(client, {
          prefix: 'VEN-',
          typeName: 'vendor',
          fieldName: 'vendorNumber',
        })
      },
    }),
    defineField({
      name: 'companyName',
      title: 'Company Name',
      type: 'string',
      validation: (Rule) => Rule.required(),
      group: 'profile',
    }),
    defineField({
      name: 'displayName',
      title: 'Display Name',
      description: 'Short name for internal use',
      type: 'string',
      group: 'profile',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'profile',
      options: {
        list: [
          {title: '✅ Active', value: 'active'},
          {title: '⏸️ On Hold', value: 'on_hold'},
          {title: '❌ Inactive', value: 'inactive'},
          {title: '🚫 Suspended', value: 'suspended'},
        ],
        layout: 'radio',
      },
      initialValue: 'active',
    }),
    defineField({
      name: 'website',
      title: 'Website',
      type: 'url',
      group: 'profile',
    }),
    defineField({
      name: 'businessType',
      title: 'Business Type',
      type: 'string',
      group: 'profile',
    }),
    defineField({
      name: 'yearsInBusiness',
      title: 'Years in Business',
      type: 'number',
      group: 'profile',
    }),
    defineField({
      name: 'primaryContact',
      title: 'Primary Contact',
      type: 'object',
      group: 'contacts',
      options: {columns: 2},
      fields: [
        defineField({name: 'name', title: 'Name', type: 'string'}),
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'email', title: 'Email', type: 'string'}),
        defineField({name: 'phone', title: 'Phone', type: 'string'}),
        defineField({name: 'mobile', title: 'Mobile', type: 'string'}),
      ],
    }),
    defineField({
      name: 'accountingContact',
      title: 'Accounting Contact',
      type: 'object',
      group: 'contacts',
      options: {columns: 2},
      fields: [
        defineField({name: 'name', title: 'Name', type: 'string'}),
        defineField({name: 'email', title: 'Email', type: 'string'}),
        defineField({name: 'phone', title: 'Phone', type: 'string'}),
      ],
    }),
    defineField({
      name: 'businessAddress',
      title: 'Business Address',
      type: 'object',
      group: 'addresses',
      options: {columns: 2},
      fields: [
        defineField({name: 'street', title: 'Street', type: 'string'}),
        defineField({name: 'city', title: 'City', type: 'string'}),
        defineField({name: 'state', title: 'State / Province', type: 'string'}),
        defineField({name: 'zip', title: 'ZIP / Postal Code', type: 'string'}),
        defineField({name: 'country', title: 'Country', type: 'string'}),
      ],
    }),
    defineField({
      name: 'shippingAddress',
      title: 'Shipping Address',
      type: 'object',
      group: 'addresses',
      options: {columns: 2},
      fields: [
        defineField({name: 'street', title: 'Street', type: 'string'}),
        defineField({name: 'city', title: 'City', type: 'string'}),
        defineField({name: 'state', title: 'State / Province', type: 'string'}),
        defineField({name: 'zip', title: 'ZIP / Postal Code', type: 'string'}),
        defineField({name: 'country', title: 'Country', type: 'string'}),
      ],
    }),
    defineField({
      name: 'pricingTier',
      title: 'Pricing Tier',
      type: 'string',
      group: 'pricing',
      options: {
        list: [
          {title: '🥉 Standard (20% off retail)', value: 'standard'},
          {title: '🥈 Preferred (30% off retail)', value: 'preferred'},
          {title: '🥇 Platinum (40% off retail)', value: 'platinum'},
          {title: '💎 Custom Pricing', value: 'custom'},
        ],
      },
      initialValue: 'standard',
    }),
    defineField({
      name: 'customDiscountPercentage',
      title: 'Custom Discount %',
      type: 'number',
      group: 'pricing',
      hidden: ({document}) => document?.pricingTier !== 'custom',
      validation: (Rule) => Rule.min(0).max(100),
    }),
    defineField({
      name: 'paymentTerms',
      title: 'Payment Terms',
      type: 'string',
      group: 'pricing',
      options: {
        list: [
          {title: 'Due on Receipt', value: 'due_on_receipt'},
          {title: 'Net 15', value: 'net_15'},
          {title: 'Net 30', value: 'net_30'},
          {title: 'Net 60', value: 'net_60'},
          {title: 'Net 90', value: 'net_90'},
        ],
      },
      initialValue: 'net_30',
    }),
    defineField({
      name: 'creditLimit',
      title: 'Credit Limit ($)',
      type: 'number',
      group: 'pricing',
    }),
    defineField({
      name: 'currentBalance',
      title: 'Current Balance ($)',
      type: 'number',
      readOnly: true,
      group: 'pricing',
      initialValue: 0,
    }),
    defineField({
      name: 'taxExempt',
      title: 'Tax Exempt?',
      type: 'boolean',
      initialValue: false,
      group: 'tax',
    }),
    defineField({
      name: 'taxExemptCertificate',
      title: 'Tax Exempt Certificate',
      type: 'file',
      group: 'tax',
      hidden: ({document}) => !document?.taxExempt,
    }),
    defineField({
      name: 'taxId',
      title: 'Tax ID / EIN',
      type: 'string',
      group: 'tax',
    }),
    defineField({
      name: 'minimumOrderAmount',
      title: 'Minimum Order ($)',
      type: 'number',
      group: 'orderSettings',
      initialValue: 500,
    }),
    defineField({
      name: 'allowBackorders',
      title: 'Allow Backorders',
      type: 'boolean',
      initialValue: true,
      group: 'orderSettings',
    }),
    defineField({
      name: 'autoApproveOrders',
      title: 'Auto-approve Orders Under Credit Limit',
      type: 'boolean',
      description: 'Auto-approve orders under credit limit',
      initialValue: false,
      group: 'orderSettings',
    }),
    defineField({
      name: 'portalEnabled',
      title: 'Portal Enabled',
      type: 'boolean',
      description: 'Allow vendor to place orders via portal',
      initialValue: false,
      group: 'portal',
    }),
    defineField({
      name: 'portalUsers',
      title: 'Portal Users',
      type: 'array',
      group: 'portal',
      of: [
        defineField({
          type: 'object',
          name: 'portalUser',
          fields: [
            defineField({name: 'email', title: 'Email', type: 'string'}),
            defineField({name: 'name', title: 'Name', type: 'string'}),
            defineField({
              name: 'role',
              title: 'Role',
              type: 'string',
              options: {
                list: ['Admin', 'Ordering', 'View Only'],
              },
            }),
            defineField({name: 'active', title: 'Active', type: 'boolean', initialValue: true}),
          ],
        }),
      ],
    }),
    defineField({
      name: 'accountManager',
      title: 'Account Manager',
      description: 'Staff member managing this account',
      type: 'string',
      group: 'tracking',
    }),
    defineField({
      name: 'onboardedAt',
      title: 'Onboarded At',
      type: 'datetime',
      group: 'tracking',
    }),
    defineField({
      name: 'lastOrderDate',
      title: 'Last Order Date',
      type: 'datetime',
      readOnly: true,
      group: 'tracking',
    }),
    defineField({
      name: 'totalOrders',
      title: 'Total Orders',
      type: 'number',
      readOnly: true,
      initialValue: 0,
      group: 'tracking',
    }),
    defineField({
      name: 'totalRevenue',
      title: 'Total Revenue',
      type: 'number',
      readOnly: true,
      initialValue: 0,
      group: 'tracking',
    }),
    defineField({
      name: 'internalNotes',
      title: 'Internal Notes',
      type: 'text',
      rows: 4,
      group: 'tracking',
    }),
    defineField({
      name: 'applicationRef',
      title: 'Linked Application',
      type: 'reference',
      to: [{type: 'vendorApplication'}],
      readOnly: true,
      group: 'tracking',
    }),
    // Legacy & compatibility fields
    defineField({
      name: 'passwordHash',
      title: 'Password Hash',
      type: 'string',
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'logo',
      title: 'Company Logo',
      type: 'image',
      options: {hotspot: true},
    }),
    defineField({
      name: 'roles',
      title: 'Access Roles',
      type: 'array',
      of: [{type: 'string'}],
      initialValue: ['vendor'],
      options: {
        list: [
          {title: 'Vendor', value: 'vendor'},
          {title: 'Customer', value: 'customer'},
          {title: 'Admin', value: 'admin'},
        ],
      },
    }),
    defineField({
      name: 'orders',
      title: 'Orders',
      type: 'array',
      of: [{type: 'vendorOrderSummary'}],
      readOnly: true,
    }),
    defineField({
      name: 'quotes',
      title: 'Submitted Quotes',
      type: 'array',
      of: [{type: 'vendorQuoteSummary'}],
      readOnly: true,
    }),
    defineField({
      name: 'assignedCustomers',
      title: 'Assigned Customers',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'customer'}]}],
    }),
    defineField({
      name: 'lastLogin',
      title: 'Last Login Date',
      type: 'datetime',
      readOnly: true,
    }),
    defineField({
      name: 'active',
      title: 'Active Status',
      type: 'boolean',
      initialValue: true,
    }),
  ],
})
