import { defineType, defineField } from 'sanity'
import OrderCartItemMetadataInput from '../../components/inputs/OrderCartItemMetadataInput'

export const orderCartItemType = defineType({
  name: 'orderCartItem',
  title: 'Cart Item',
  type: 'object',
  fields: [
    defineField({ name: 'id', type: 'string', title: 'Product ID / Slug', readOnly: true }),
    defineField({ name: 'productSlug', type: 'string', title: 'Product Slug', readOnly: true }),
    defineField({ name: 'stripeProductId', type: 'string', title: 'Stripe Product ID', readOnly: true }),
    defineField({ name: 'stripePriceId', type: 'string', title: 'Stripe Price ID', readOnly: true }),
    defineField({ name: 'sku', type: 'string', title: 'SKU' }),
    defineField({ name: 'name', type: 'string', title: 'Display Name' }),
    defineField({ name: 'productName', type: 'string', title: 'Stripe Product Name', readOnly: true }),
    defineField({ name: 'description', type: 'string', title: 'Stripe Line Description', readOnly: true }),
    defineField({ name: 'image', type: 'url', title: 'Product Image URL', readOnly: true }),
    defineField({ name: 'productUrl', type: 'string', title: 'Product URL', readOnly: true }),
    defineField({
      name: 'productRef',
      type: 'reference',
      title: 'Sanity Product',
      to: [{ type: 'product' }],
      readOnly: true,
    }),
    defineField({ name: 'optionSummary', type: 'string', title: 'Selected Options', readOnly: true }),
    defineField({
      name: 'optionDetails',
      type: 'array',
      title: 'Option Details',
      readOnly: true,
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'upgrades',
      type: 'array',
      title: 'Upgrades',
      readOnly: true,
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'customizations',
      type: 'array',
      title: 'Customizations',
      readOnly: true,
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({ name: 'price', type: 'number', title: 'Unit Price' }),
    defineField({ name: 'quantity', type: 'number', title: 'Quantity' }),
    defineField({ name: 'lineTotal', type: 'number', title: 'Line Total', readOnly: true }),
    defineField({ name: 'total', type: 'number', title: 'Item Total (incl. adjustments)', readOnly: true }),
    defineField({ name: 'categories', title: 'Category Tags', type: 'array', of: [{ type: 'string' }] }),
    defineField({
      name: 'validationIssues',
      title: 'Validation Issues',
      type: 'array',
      readOnly: true,
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'metadata',
      title: 'Raw Metadata',
      type: 'array',
      of: [{ type: 'orderCartItemMeta' }],
      components: {
        input: OrderCartItemMetadataInput,
      },
    }),
  ],
})
