export const contentSchemaFiles = [
  'packages/sanity-config/src/schemaTypes/documents/product.ts',
  'packages/sanity-config/src/schemaTypes/documents/productVariant.tsx',
  'packages/sanity-config/src/schemaTypes/documents/productBundle.ts',
  'packages/sanity-config/src/schemaTypes/documents/collection.tsx',
  'packages/sanity-config/src/schemaTypes/documents/page.ts',
  'packages/sanity-config/src/schemaTypes/documents/colorTheme.tsx',
  'packages/sanity-config/src/schemaTypes/documents/blog/blogPost.ts',
  'packages/sanity-config/src/schemaTypes/documents/blog/blogCategory.ts',
  'packages/sanity-config/src/schemaTypes/documents/downloadResource.ts',
  'packages/sanity-config/src/schemaTypes/documents/altText.ts',
  'packages/sanity-config/src/schemaTypes/singletons/homeType.ts',
  'packages/sanity-config/src/schemaTypes/singletons/siteSettingsType.ts',
  'packages/sanity-config/src/schemaTypes/documents/navigationMenu.ts',
  'packages/sanity-config/src/schemaTypes/documents/legalContent.ts',
  'packages/sanity-config/src/schemaTypes/documents/storePolicy.ts',
]

export const forbiddenFieldNames = [
  'price',
  'compareAtPrice',
  'cost',
  'inventory',
  'inventoryQuantity',
  'quantityOnHand',
  'quantityReserved',
  'trackInventory',
  'manageInventory',
  'allowBackorder',
  'lowStockThreshold',
  'shippingConfig',
  'shippingRate',
  'shippingRates',
  'cart',
  'cartItems',
  'checkoutSessionId',
  'checkoutStatus',
  'orderNumber',
  'orderStatus',
  'paymentStatus',
  'fulfillmentStatus',
  'totalAmount',
  'totalCents',
  'subtotalCents',
  'shippingCents',
  'taxCents',
  'discountCents',
  'currencyCode',
  'stripeProductId',
  'stripePriceId',
]

export const forbiddenTypeNames = [
  'priceRange',
  'inventoryType',
  'inventoryRecord',
  'inventoryTransaction',
  'checkoutSession',
  'abandonedCheckout',
  'order',
  'orderCartItem',
  'orderCartItemMeta',
  'shippingAddress',
  'shipmentWeight',
  'packageDimensions',
  'stripePriceSnapshot',
  'stripeOrderSummary',
]

export const forbiddenDocumentTypeReferences = ['order', 'invoice', 'quote', 'vendorOrder', 'purchaseOrder']

export const referenceLookaheadLines = 12
